// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMS0YKjdLXmqGvOPlieTtHNRrg4zhw20',
    appId: '1:834292485167:web:47796daa4e099f00124ada',
    messagingSenderId: '834292485167',
    projectId: 'projet2fa',
    authDomain: 'projet2fa.firebaseapp.com',
    storageBucket: 'projet2fa.firebasestorage.app',
    measurementId: 'G-2R2QB83PJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEagU4xPKhlFuIk_ZVY9D_XoVl2_AWLbg',
    appId: '1:834292485167:android:9fd2987e91a6ee46124ada',
    messagingSenderId: '834292485167',
    projectId: 'projet2fa',
    storageBucket: 'projet2fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6fOwhyGQrLxCS5SLcWuyEKRlVhAmsRng',
    appId: '1:834292485167:ios:dead027b66f756dd124ada',
    messagingSenderId: '834292485167',
    projectId: 'projet2fa',
    storageBucket: 'projet2fa.firebasestorage.app',
    iosBundleId: 'com.example.fidelyKey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6fOwhyGQrLxCS5SLcWuyEKRlVhAmsRng',
    appId: '1:834292485167:ios:dead027b66f756dd124ada',
    messagingSenderId: '834292485167',
    projectId: 'projet2fa',
    storageBucket: 'projet2fa.firebasestorage.app',
    iosBundleId: 'com.example.fidelyKey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_afsddS8lHtgElXrxVE5XO2UtIDgbArA',
    appId: '1:834292485167:web:35a3a460d6e6986d124ada',
    messagingSenderId: '834292485167',
    projectId: 'projet2fa',
    authDomain: 'projet2fa.firebaseapp.com',
    storageBucket: 'projet2fa.firebasestorage.app',
    measurementId: 'G-DTQ2HBMMX7',
  );
}
